version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - SERVER_URL=http://server:8081
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3