# Docker Compose override for Langfuse integration
# This file extends docker-compose.yml to add Langfuse network connectivity
#
# Usage: docker compose -f docker-compose.yml -f docker-compose.langfuse.yml up -d

networks:
  langfuse_default:
    external: true

services:
  weather-agent:
    networks:
      - weather-network
      - langfuse_default
    environment:
      # Override Langfuse host to use Docker network name
      - LANGFUSE_HOST=http://langfuse-web:3000
      # Enable telemetry by default when using this override
      - ENABLE_TELEMETRY=true